# @name get
GET http://localhost:8080/

###

# @name POST
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "Ismael Dias",
  "username": "Ismael",
  "password": "12345"
}

###

# @name task
POST http://localhost:8080/tasks/
Content-Type: application/json

{
  "description": "Teste mael",
  "title": "Ismael Dias",
  "priority": "ALTA",
  "startAt": "2023-10-12T22:22:00",
  "endAt": "2023-10-12T23:22:00",
  "idUser": "e97a4985-5318-4f75-ab61-8b8001def2e5"
}

###

# @name task
PUT  http://localhost:8080/tasks/f3fb7bfe-79ed-4764-b9c9-38af41533e9b
Content-Type: application/json

{
  "title": "Teste teste teste ",
}